model:
  arch: blip_nlvr
  model_type: nlvr
  load_finetuned: False

datasets:
  nlvr: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 384
        eval:
          name: "blip_image_eval"
          image_size: 384
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

run:
  task: multimodal_classification

  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 5e-6
  min_lr: 1e-6
  weight_decay: 0.05
  # warmup_lr: 1e-5
  # warmup_steps: 650
  max_epoch: 5

  seed: 42
  batch_size_train: 16
  batch_size_eval: 64
  num_workers: 8
  log_freq: 200

  amp: False
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # distribution-specific
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  output_dir: "output/original/blip/nlvr"
