model:
  arch: albef_retrieval
  model_type: coco
  load_finetuned: False

  queue_size: 65536

run:
  task: retrieval
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  weight_decay: 0.05

  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  # model specific
  k_test: 256

  output_dir: "./output/original/albef/retrieval_coco"

  max_epoch: 5
  log_freq: 200

  # dataloading
  num_workers: 8
  batch_size_train: 32
  batch_size_eval: 64
  
  # distribution
  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True
  use_dist_eval_sampler: False

  # misc
  seed: 42
  amp: False
  resume_ckpt_path: null
  evaluate: False

datasets:
  coco_retrieval: # name of the dataset builder
    vis_processor:
        train:
          name: "blip_image_train"
          image_size: 384
        eval:
          name: "blip_image_eval"
          image_size: 384
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"

